--○ 직원 정보 테이블 생성
CREATE TABLE MEMBER
( MID       NUMBER(3)       -- 숫자 3자리
, POSITION  VARCHAR2(30)
, NAME      VARCHAR2(30)
, TEL       VARCHAR2(30)
, EMAIL     VARCHAR2(100)
);


--○ 제약조건 수정
ALTER TABLE MEMBER 
ADD CONSTRAINT MEMBER_MID_PK PRIMARY KEY(MID);


--○ 직원 정보 등록
INSERT INTO MEMBER(MID, POSITION, NAME, TEL, EMAIL)
VALUES(1, '사원', '고경희', '010-1111-2222', 'GO@TEST.COM');

INSERT INTO MEMBER(MID, POSITION, NAME, TEL, EMAIL)
VALUES(2, '대리', '서진수', '010-3333-4444', 'JINSU@TEST.COM');

COMMIT;


--○ 직원 리스트 출력
SELECT MID, POSITION, NAME, TEL, EMAIL
FROM MEMBER
ORDER BY NAME;


--○ 직원 검색
SELECT MID, POSITION, NAME, TEL, EMAIL
FROM MEMBER
--WHERE MID=1
--WHERE POSITION LIKE '%' || '대' || '%'
--WHERE NAME LIKE '%' || '고' || '%'
--WHERE TEL LIKE '%' || '010' || '%'
WHERE EMAIL LIKE '%' || UPPER('TEST') || '%'
   OR EMAIL LIKE '%' || LOWER('TEST') || '%'
ORDER BY NAME;


--○ 직원 정보 수정
UPDATE MEMBER
SET MID=1, POSITION='사장', NAME='고로로', TEL='010-1111-2222', EMAIL='MMMMK@NAVER.COM'
WHERE MID=1;


--○ 직원 정보 삭제
DELETE 
FROM MEMBER
WHERE MID=3;


--○ 커밋
COMMIT;